using HunterFreemanDev.ClassLibrary.PlainTextEditor;

namespace HunterFreemanDev.ClassLibrary.Store.PlainTextEditor;

public record RegisterPlainTextEditorAction(PlainTextEditorRecord PlainTextEditorRecord);
