using HunterFreemanDev.ClassLibrary.PlainTextEditor;

namespace HunterFreemanDev.ClassLibrary.Store.PlainTextEditor;

public record UnregisterPlainTextEditorAction(PlainTextEditorRecord PlainTextEditorRecord);
