using HunterFreemanDev.ClassLibrary.DebugCssClasses;

namespace HunterFreemanDev.ClassLibrary.Store.DebugCssClasses;

public record RegisterDebugCssClassRecordAction(DebugCssClassRecord DebugCssClassRecord);
